languageCode = "en-us"
title = "Real Wellness"
baseURL = "https://getreallywell.com"
theme = "Massively"
googleanalytics = ""
disqusShortname = ""

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"

# Below parameters can be set to override default post settings
# [params.posts]
#     foldername = "post"
#     pagesize = "6"
#     featuredpost = "true"

[languages]
[languages.en]
  languageName = "English"

[author]
    name = "Moira Walker"
    homepage = "https://wander.haus"

# If porting an existing theme
# [original]
#    author = "HTML5UP"
#    homepage = "https://html5up.net"
#    repo = "https://html5up.net/massively"